/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facepp_demo_util_ImageCV */

#ifndef _Included_com_facepp_demo_util_ImageCV
#define _Included_com_facepp_demo_util_ImageCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facepp_demo_util_ImageCV
 * Method:    imageCVProcess
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_facepp_demo_util_ImageCV_imageCVProcess
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif